### ISSUE TITLE
Converting more NMKD ESRGAN Models to ONNX

### ISSUE THREAD

**Issue by thomasza92** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#28]
Is it possible to convert `4x_NMKD-Yandere4_120000_G.pth` and  `4x_NMKD-YandereNeoXL_200k.pth` models to onnx? If so what is procedure? Or can you add to repository? Thank you for all your hard work!

**Comment by yuvraj108c** [comment]
1. Download the model into comfyui `models/upscale_models`

2. Modify `export_onnx.py`

https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/bdad3d789c1cc9e80b6f42e27870d2f64d050f82/export_onnx.py#L100C6-L100C48

https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/bdad3d789c1cc9e80b6f42e27870d2f64d050f82/export_onnx.py#L115C1-L115C61

3. Run `export_onnx.py` then build the tensorrt engine from it

**Comment by Kobak24** [comment]
I got this error trying to convert the same pth to onnx:

```
C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'triton'
WARNING: comfy_extras.chainner_models is deprecated and has been replaced by the spandrel library.
Traceback (most recent call last):
  File "E:\_AI\ComfyUI\export_onnx.py", line 113, in <module>
    torch.onnx.export(upscale_model,
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\onnx\utils.py", line 551, in export
    _export(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\onnx\utils.py", line 1625, in _export
    with exporter_context(model, training, verbose):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\onnx\utils.py", line 180, in exporter_context
    with select_model_mode_for_export(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\onnx\utils.py", line 141, in disable_apex_o2_state_dict_hook
    for module in model.modules():
                  ^^^^^^^^^^^^^
AttributeError: 'ImageModelDescriptor' object has no attribute 'modules'

```

Seems like I'm not passing a .pth file while it is a working pth file. Not sure if we need to pass the full model or just the state dictionary at this point

**Comment by mrjuan1** [comment]
Don't mean to mindlessly bump this, but `export_onnx.py` doesn't work at all anymore.

**Comment by yuvraj108c** [comment]
> Don't mean to mindlessly bump this, but `export_onnx.py` doesn't work at all anymore.

hmm, what errors are you getting?
