### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_input_shape'

### ISSUE THREAD

**Issue by jiliu112** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#29]
Traceback (most recent call last):
  File "/data/liuji/projects/flux/ComfyUI_flux/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/liuji/projects/flux/ComfyUI_flux/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/liuji/projects/flux/ComfyUI_flux/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/liuji/projects/flux/ComfyUI_flux/custom_nodes/ComfyUI-Upscaler-Tensorrt/__init__.py", line 80, in main
  File "/data/liuji/projects/flux/ComfyUI_flux/custom_nodes/ComfyUI-Upscaler-Tensorrt/utilities.py", line 248, in allocate_buffers
    self.context.set_input_shape(name, shape)
AttributeError: 'NoneType' object has no attribute 'set_input_shape'

**Comment by yuvraj108c** [comment]
have you followed all instructions in the readme?
