### ISSUE TITLE
'UpscalerTensorrt' object has no attribute 'engine_label'

### ISSUE THREAD

**Issue by Trinistryx** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#30]
UpscalerTensorrt
'UpscalerTensorrt' object has no attribute 'engine_label'

--------------------------------------------------------
Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing !!! 'UpscalerTensorrt' object has no attribute 'engine_label'
Traceback (most recent call last):
  File "D:\JHON\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JHON\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JHON\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\JHON\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JHON\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 70, in main
    if (not hasattr(self, 'engine') or self.engine_label != engine):
                                       ^^^^^^^^^^^^^^^^^
AttributeError: 'UpscalerTensorrt' object has no attribute 'engine_label'

--------------------------------------------------------

![cap](https://github.com/user-attachments/assets/d64a34cd-7f0d-4583-b9f3-688727442ac3)

**Comment by yuvraj108c** [comment]
Hi, another user reported this issue a while back, and I can't seem to reproduce it.

Is this the first time you're installing this node, or you updated and then getting this issue?

**Comment by revmouse** [comment]
I have the same issue. The node is installed, the engine is built and placed in the correct directory.

**Comment by Trinistryx** [comment]
> Hola, otro usuario informó de este problema hace un tiempo y parece que no puedo reproducirlo.
> 
> ¿Es la primera vez que instala este nodo o lo actualizó y luego tiene este problema?

if it is the first time I install the node, I also did everything correctly

**Comment by vivi-gomez** [comment]
I maybe wrong, Did you install tensorrt==10.5.0? you may try pip install tensorrt==10.4.0

> > Hola, otro usuario informó de este problema hace un tiempo y parece que no puedo reproducirlo.
> > ¿Es la primera vez que instala este nodo o lo actualizó y luego tiene este problema?
> 
> if it is the first time I install the node, I also did everything correctly

**Comment by PitmasterAI** [comment]
Well, after getting the Engine together, installing Python, selecting the correct paths, I was able to make them work. The solution using PinoKio is this by not having a console.

PINOKIO CONFYUI
1-Open Confyui Manger Menu
2- Install PIP Packages 
3-Write "tensorrt==10.4.0"

![Solucion](https://github.com/user-attachments/assets/125b6d81-f70a-42f9-bc9d-fda286775aed)
