### ISSUE TITLE
ERROR: inference failed. - dimensions are not specified: input

### ISSUE THREAD

**Issue by twistmachine** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#31]
Hello
Trying to test your node but i get this error
i used the command to build the engine from onnx
Thanks for your help

![image](https://github.com/user-attachments/assets/a261396d-550b-4cc0-8a60-c1cafda6d0b2)

got prompt
Using cached TensorRT engine: C:\Users\...\ComfyUI\models\tensorrt\upscaler\realesrgan-x4.engine
[E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: satisfyProfile. Set dimension [1,3,2048,2048] for tensor input does not satisfy any optimization profiles. Valid range for profile 0: [1,3,256,256]..[1,3,1280,1280].)
[E] IExecutionContext::enqueueV3: Error Code 3: API Usage Error (Parameter check failed, condition: inputDimensionSpecified && inputShapesSpecified. Not all shapes are specified. Following input tensors' dimensions are not specified: input.)
!!! Exception during processing !!! ERROR: inference failed.
Traceback (most recent call last):
  File "C:\Users\...\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\...\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 89, in main
    result = self.engine.infer({"input": img}, cudaStream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\utilities.py", line 266, in infer
    raise ValueError("ERROR: inference failed.")
ValueError: ERROR: inference failed.

Prompt executed in 0.33 seconds

**Comment by yuvraj108c** [comment]
Hi, the tensorrt engine supports images from 256 to 1280 pixels,
Either resize the input image, or rebuild the tensorrt engine by increasing the maximum resolution in [export_trt.py](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/master/export_trt.py)

```python
            {"input": [(1,3,256,256), (1,3,512,512), (1,3,1280,1280)]}, # any sizes from 256x256 to 1280x1280
```
