### ISSUE TITLE
[E] 1: [stdArchiveReader.cpp::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 239)

### ISSUE THREAD

**Issue by kairin** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#34]
now another issue...

```
Loading TensorRT engine: /home/k/comfy/models/tensorrt/upscaler/4x_foolhardy_Remacri.engine
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[E] 1: [stdArchiveReader.cpp::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 239)
[!] Could not deserialize engine. See log for details.
!!! Exception during processing !!! Could not deserialize engine. See log for details.
Traceback (most recent call last):
  File "/home/k/comfy/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/k/comfy/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/k/comfy/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/k/comfy/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/__init__.py", line 72, in main
    self.engine.load()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/utilities.py", line 227, in load
    self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
  File "<string>", line 3, in engine_from_bytes
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 665, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.

Prompt executed in 55.40 seconds
```

_Originally posted by @kairin in https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/issues/33#issuecomment-2524818303_

**Comment by kairin** [comment]
something tells me the https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/master/export_trt_from_directory.py is broken... but i can't figure out why it doesn't work...

```

.              .bashrc  .git-credentials  .landscape   .nv              .sudo_as_admin_successful  forge
..             .cache   .gitconfig        .lesshst     .profile         backupCustom_Nodes         snap
.bash_history  .config  .idlerc           .local       .pyenv           comfy
.bash_logout   .fonts   .keras            .motd_shown  .python_history  discord-msgs
Running (pyenv virtualenvs) this Lists all Python virtualenvs found in (/home/k/.pyenv/versions/*) in the next line
Running now.
  3.10.16/envs/ven1 (created from /home/k/.pyenv/versions/3.10.16)
  ven1 (created from /home/k/.pyenv/versions/3.10.16)
We are running (pyenv activate) to activate the listed environment (ven1) next.
Running now
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
Sat Dec  7 11:04:30 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.72                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:0B:00.0  On |                  N/A |
|  0%   39C    P2             15W /  320W |   14272MiB /  16376MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        82      G   /Xwayland                                   N/A      |
|    0   N/A  N/A    574692      C   /python3.10                                 N/A      |
+-----------------------------------------------------------------------------------------+
VIRTUAL_ENV=/home/k/.pyenv/versions/3.10.16/envs/ven1
PYENV_VIRTUAL_ENV=/home/k/.pyenv/versions/3.10.16/envs/ven1
  3.10.16/envs/ven1 (created from /home/k/.pyenv/versions/3.10.16)
* ven1 (created from /home/k/.pyenv/versions/3.10.16)
.              .bashrc  .git-credentials  .landscape   .nv              .sudo_as_admin_successful  forge
..             .cache   .gitconfig        .lesshst     .profile         backupCustom_Nodes         snap
.bash_history  .config  .idlerc           .local       .pyenv           comfy
.bash_logout   .fonts   .keras            .motd_shown  .python_history  discord-msgs
.               CODEOWNERS       comfy_execution    extra_model_paths.yaml.example  node_helpers.py   styles
..              CONTRIBUTING.md  comfy_extras       fix_torch.py                    nodes.py          temp
.ci             LICENSE          comfyui.log        folder_paths.py                 notebooks         tests
.git            README.md        comfyui.prev.log   input                           output            tests-unit
.gitattributes  __pycache__      comfyui.prev2.log  latent_preview.py               pytest.ini        user
.github         api_server       cuda_malloc.py     main.py                         requirements.txt  utils
.gitignore      app              custom_nodes       models                          script_examples   web
.pylintrc       comfy            execution.py       new_updater.py                  server.py
(ven1) k@4080SUPER:~/comfy$ cd custom_nodes
(ven1) k@4080SUPER:~/comfy/custom_nodes$ ls
ComfyUI-Impact-Pack  ComfyUI-Manager  ComfyUI-Upscaler-Tensorrt  comfy_mtb  comfyui-reactor-node  comfyui_gr85
(ven1) k@4080SUPER:~/comfy/custom_nodes$ cd ComfyUI-Upscaler-Tensorrt
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ ls
LICENSE  README.md  __init__.py  __pycache__  assets  export_onnx.py  export_trt.py  export_trt_from_directory.py  requirements.txt  utilities.py
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ ./export_trt_from_directory.py
./export_trt_from_directory.py: line 1: import: command not found
./export_trt_from_directory.py: line 2: import: command not found
./export_trt_from_directory.py: line 3: import: command not found
./export_trt_from_directory.py: line 4: from: command not found
./export_trt_from_directory.py: line 5: $'\r': command not found
./export_trt_from_directory.py: line 6: syntax error near unexpected token `('
'/export_trt_from_directory.py: line 6: `def export_trt(trt_path=None, onnx_path=None, use_fp16=True):
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ export_trt_from_directory.py
export_trt_from_directory.py: command not found
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt_from_directory.py
Choose an option:
1. Convert a single ONNX file
2. Convert all ONNX files in a directory
Enter your choice (1 or 2): 2
Enter the directory path containing ONNX models (e.g ./onnx_models/): /home/k/comfy/models/upscale_models
Enter the directory path to save the TensorRT engines (e.g ./trt_engine/): /home/k/comfy/models/tensorrt/upscaler/
Converting /home/k/comfy/models/upscale_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx to /home/k/comfy/models/tensorrt/upscaler/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
Building TensorRT engine for /home/k/comfy/models/upscale_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx: /home/k/comfy/models/tensorrt/upscaler/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
[!] Invalid inputs were provided to the optimization profile: {'input'}
    Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
Traceback (most recent call last):
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 62, in <module>
    export_trt()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 43, in export_trt
    ret = engine.build(
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/utilities.py", line 205, in build
    calib_profile = profile.fill_defaults(network[1]).to_trt(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/backend/trt/profile.py", line 190, in to_trt
    G_LOGGER.critical(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid inputs were provided to the optimization profile: {'input'}
Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt_from_directory.py
Choose an option:
1. Convert a single ONNX file
2. Convert all ONNX files in a directory
Enter your choice (1 or 2): 2
Enter the directory path containing ONNX models (e.g ./onnx_models/): /home/k/comfy/models/upscale_models/
Enter the directory path to save the TensorRT engines (e.g ./trt_engine/): /home/k/comfy/models/tensorrt/upscaler/
Converting /home/k/comfy/models/upscale_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx to /home/k/comfy/models/tensorrt/upscaler/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
Building TensorRT engine for /home/k/comfy/models/upscale_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx: /home/k/comfy/models/tensorrt/upscaler/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
[!] Invalid inputs were provided to the optimization profile: {'input'}
    Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
Traceback (most recent call last):
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 62, in <module>
    export_trt()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 43, in export_trt
    ret = engine.build(
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/utilities.py", line 205, in build
    calib_profile = profile.fill_defaults(network[1]).to_trt(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/backend/trt/profile.py", line 190, in to_trt
    G_LOGGER.critical(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid inputs were provided to the optimization profile: {'input'}
Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt_from_directory.py
Choose an option:
1. Convert a single ONNX file
2. Convert all ONNX files in a directory
Enter your choice (1 or 2): 2
Enter the directory path containing ONNX models (e.g ./onnx_models/): ./onnx_models/
Enter the directory path to save the TensorRT engines (e.g ./trt_engine/):
Traceback (most recent call last):
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 62, in <module>
    export_trt()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 24, in export_trt
    os.makedirs(trt_dir)
  File "/home/k/.pyenv/versions/3.10.16/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt_from_directory.py
Choose an option:
1. Convert a single ONNX file
2. Convert all ONNX files in a directory
Enter your choice (1 or 2): 2
Enter the directory path containing ONNX models (e.g ./onnx_models/): ./onnx_models/
Enter the directory path to save the TensorRT engines (e.g ./trt_engine/): ./onnx_models/
Converting ./onnx_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx to ./onnx_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
Building TensorRT engine for ./onnx_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.onnx: ./onnx_models/4xHFA2k_ludvae_realplksr_dysample_256_fp32_fullyoptimized.engine
[!] Invalid inputs were provided to the optimization profile: {'input'}
    Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
Traceback (most recent call last):
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 62, in <module>
    export_trt()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt_from_directory.py", line 43, in export_trt
    ret = engine.build(
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/utilities.py", line 205, in build
    calib_profile = profile.fill_defaults(network[1]).to_trt(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/backend/trt/profile.py", line 190, in to_trt
    G_LOGGER.critical(
  File "/home/k/.pyenv/versions/ven1/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Invalid inputs were provided to the optimization profile: {'input'}
Note: Inputs available in the TensorRT network are: {'onnx::Conv_0'}
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$

```

**Comment by kairin** [comment]
the following seems fine

```
.              .config           .landscape   .pyenv                     forge
..             .fonts            .lesshst     .python_history            snap
.bash_history  .git-credentials  .local       .sudo_as_admin_successful
.bash_logout   .gitconfig        .motd_shown  backupCustom_Nodes
.bashrc        .idlerc           .nv          comfy
.cache         .keras            .profile     discord-msgs
Running (pyenv virtualenvs) this Lists all Python virtualenvs found in (/home/k/.pyenv/versions/*) in the next line
Running now.
  3.10.16/envs/ven1 (created from /home/k/.pyenv/versions/3.10.16)
  ven1 (created from /home/k/.pyenv/versions/3.10.16)
We are running (pyenv activate) to activate the listed environment (ven1) next.
Running now
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
Sat Dec  7 11:09:51 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.72                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:0B:00.0  On |
  N/A |
|  0%   39C    P2             15W /  320W |   14298MiB /  16376MiB |      1%      Default |
|                                         |                        |
  N/A |
+-----------------------------------------+------------------------+----------------------+


+-----------------------------------------------------------------------------------------+
| Processes:
      |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        82      G   /Xwayland                                   N/A      |
|    0   N/A  N/A    574692      C   /python3.10                                 N/A      |
+-----------------------------------------------------------------------------------------+
VIRTUAL_ENV=/home/k/.pyenv/versions/3.10.16/envs/ven1
PYENV_VIRTUAL_ENV=/home/k/.pyenv/versions/3.10.16/envs/ven1
  3.10.16/envs/ven1 (created from /home/k/.pyenv/versions/3.10.16)
* ven1 (created from /home/k/.pyenv/versions/3.10.16)
.              .config           .landscape   .pyenv                     forge
..             .fonts            .lesshst     .python_history            snap
.bash_history  .git-credentials  .local       .sudo_as_admin_successful
.bash_logout   .gitconfig        .motd_shown  backupCustom_Nodes
.bashrc        .idlerc           .nv          comfy
.cache         .keras            .profile     discord-msgs
.                comfy_execution                 node_helpers.py
..               comfy_extras                    nodes.py
.ci              comfyui.log                     notebooks
.git             comfyui.prev.log                output
.gitattributes   comfyui.prev2.log               pytest.ini
.github          cuda_malloc.py                  requirements.txt
.gitignore       custom_nodes                    script_examples
.pylintrc        execution.py                    server.py
CODEOWNERS       extra_model_paths.yaml.example  styles
CONTRIBUTING.md  fix_torch.py                    temp
LICENSE          folder_paths.py                 tests
README.md        input                           tests-unit
__pycache__      latent_preview.py               user
api_server       main.py                         utils
app              models                          web
comfy            new_updater.py
(ven1) k@4080SUPER:~/comfy$ sl
Command 'sl' not found, but can be installed with:
sudo apt install sl
(ven1) k@4080SUPER:~/comfy$ ls
CODEOWNERS       api_server       comfyui.log        execution.py                    latent_preview.py  nodes.py          script_examples  tests-unit
CONTRIBUTING.md  app              comfyui.prev.log   extra_model_paths.yaml.example  main.py            notebooks         server.py        user
LICENSE          comfy            comfyui.prev2.log  fix_torch.py                    models             output            styles           utils
README.md        comfy_execution  cuda_malloc.py     folder_paths.py                 new_updater.py     pytest.ini        temp             web
__pycache__      comfy_extras     custom_nodes       input                           node_helpers.py    requirements.txt  tests
(ven1) k@4080SUPER:~/comfy$ cd custom_nodes
(ven1) k@4080SUPER:~/comfy/custom_nodes$ ls
ComfyUI-Impact-Pack  ComfyUI-Manager  ComfyUI-Upscaler-Tensorrt  comfy_mtb  comfyui-reactor-node  comfyui_gr85
(ven1) k@4080SUPER:~/comfy/custom_nodes$ cd ComfyUI-Upscaler-Tensorrt
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ ls
LICENSE    __init__.py  assets  export_onnx.py  export_trt_from_directory.py  requirements.txt
README.md  __pycache__  engine  export_trt.py   onnx                          utilities.py
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt.py
Enter the path to save the TensorRT engine (e.g ./realesrgan.engine): ./engine
Enter the path to the ONNX model (e.g ./realesrgan.onnx): ^CTraceback (most recent call last):
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt.py", line 29, in <module>
    export_trt()
  File "/home/k/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt/export_trt.py", line 9, in export_trt
    onnx_path = input("Enter the path to the ONNX model (e.g ./realesrgan.onnx): ")
KeyboardInterrupt

(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$ python export_trt.py
Enter the path to save the TensorRT engine (e.g ./realesrgan.engine): ./engine/a.engine
Enter the path to the ONNX model (e.g ./realesrgan.onnx): ./onnx/RealESRGAN_x4.onnx
Building TensorRT engine for ./onnx/RealESRGAN_x4.onnx: ./engine/a.engine
Building engine: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [01:51<00:00, 18.64s/it]
Time taken to build: 114.93237352371216 seconds
(ven1) k@4080SUPER:~/comfy/custom_nodes/ComfyUI-Upscaler-Tensorrt$                                                                                                                                                                                                                                                                                                                                               
```

**Comment by kairin** [comment]
running the .engine file can run... but issue with width and height of image and the fact that something is broken with directory conversion...

```
Requested to load SDXL
loaded completely 9.5367431640625e+25 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.53it/s]
Requested to load AutoencoderKL
loaded completely 9.5367431640625e+25 159.55708122253418 True
[ReActor] 11:20:52 - STATUS - Restoring with GPEN-BFR-2048.onnx | Face Size is set to 2048
[ReActor] 11:20:56 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
[ReActor] 11:21:19 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Prompt executed in 47.19 seconds
got prompt
loaded completely 9.5367431640625e+25 4897.0483474731445 True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:04<00:00,  6.51it/s]
Requested to load AutoencoderKL
loaded completely 9.5367431640625e+25 159.55708122253418 True
[ReActor] 11:39:27 - STATUS - Restoring with GPEN-BFR-2048.onnx | Face Size is set to 2048
[ReActor] 11:39:34 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 11:39:34 - STATUS - Analyzing Source Image...
[ReActor] 11:39:34 - STATUS - Analyzing Target Image...
[ReActor] 11:39:35 - STATUS - Source Face 0: Detected Gender -F-
[ReActor] 11:39:35 - STATUS - WRONG - Detected Gender doesn't match Condition
[ReActor] 11:39:35 - STATUS - Wrong source gender detected
[ReActor] 11:39:35 - STATUS - --Done!--
[ReActor] 11:39:35 - STATUS - Restoring with GPEN-BFR-1024.onnx | Face Size is set to 1024
Loading TensorRT engine: /home/k/comfy/models/tensorrt/upscaler/RealESRGAN_x4.onnx.engine
[ReActor] 11:39:44 - STATUS - Restoring with codeformer-v0.1.0.pth | Face Size is set to 512
1 models unloaded.
Requested to load SDXL
0 models unloaded.
loaded partially 64.0 63.99903106689453 722
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [02:41<00:00,  5.78s/it]
Requested to load AutoencoderKL
0 models unloaded.
loaded partially 64.0 63.99994659423828 0
Prompt executed in 313.46 seconds
got prompt
Requested to load SDXL
0 models unloaded.
loaded partially 64.0 63.99903106689453 722
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [02:52<00:00,  5.57s/it]
Requested to load AutoencoderKL
0 models unloaded.
loaded partially 64.0 63.99994659423828 0
[ReActor] 11:49:54 - STATUS - Restoring with GPEN-BFR-2048.onnx | Face Size is set to 2048
[ReActor] 11:50:08 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
[ReActor] 11:50:27 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
[ReActor] 11:50:28 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 11:50:28 - STATUS - Analyzing Source Image...
[ReActor] 11:50:28 - STATUS - Analyzing Target Image...
[ReActor] 11:50:28 - STATUS - Source Face 0: Detected Gender -M-
[ReActor] 11:50:28 - STATUS - OK - Detected Gender matches Condition
[ReActor] 11:50:28 - STATUS - Swapping...
[ReActor] 11:50:28 - STATUS - Face Boost is enabled
[ReActor] 11:50:28 - STATUS - Boosting the Face with GPEN-BFR-2048.onnx | Face Size is set to 2048 with Scale Factor = 16.0 and 'Bicubic' interpolation
[ReActor] 11:50:30 - STATUS - --Done!--
[ReActor] 11:50:30 - STATUS - Restoring with GPEN-BFR-1024.onnx | Face Size is set to 1024
Using cached TensorRT engine: /home/k/comfy/models/tensorrt/upscaler/RealESRGAN_x4.onnx.engine
[ReActor] 11:50:39 - STATUS - Restoring with codeformer-v0.1.0.pth | Face Size is set to 512
Requested to load AutoencoderKL
0 models unloaded.
loaded partially 64.0 63.99994659423828 0
Requested to load SDXL
0 models unloaded.
loaded partially 64.0 63.99903106689453 722
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [02:42<00:00,  5.80s/it]
Requested to load AutoencoderKL
0 models unloaded.
loaded partially 64.0 63.99994659423828 0
Prompt executed in 468.85 seconds

```

**Comment by yuvraj108c** [comment]
[E] 1: [stdArchiveReader.cpp::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 239)

for this error, you've to rebuild the tensorrt engines

I'm not sure why the export_trt_from_directory is failing, but you can fallback to the export_trt.py

In your last message, there is no error logs, so it worked?

**Comment by kairin** [comment]
> but you can fallback to the export_trt.py
> 
> In your last message, there is no error logs, so it worked?

yes, you are correct. manually generated a engine file individually.

image generates... but... it does not follow the image's width and height. 

for example, starting image is 512*512 but somehow, the upscaled image beceomes portrait instead of square.

uninstalling and reinstalling everything from scratch. will see if i come into this issue again...

**Comment by yuvraj108c** [comment]
> > but you can fallback to the export_trt.py
> > In your last message, there is no error logs, so it worked?
> 
> yes, you are correct. manually generated a engine file individually.
> 
> image generates... but... it does not follow the image's width and height.
> 
> for example, starting image is 512*512 but somehow, the upscaled image beceomes portrait instead of square.
> 
> uninstalling and reinstalling everything from scratch. will see if i come into this issue again...

I fixed the issue of wrong aspect ratio a while back, can you update the node and try again? thanks
