### ISSUE TITLE
Failed to parse ONNX model

### ISSUE THREAD

**Issue by brbbbq** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#5]
I'm getting this error when trying to export the engine:
```
Enter the path to save the TensorRT engine (.engine) file: C:\Apps\ComfyUI_windows_portable\ComfyUI\models\tensorrt\upscaler
Enter the path to the ONNX model file (.onnx): C:\Apps\ComfyUI_windows_portable\ComfyUI\models\onnx
Building TensorRT engine for C:\Apps\ComfyUI_windows_portable\ComfyUI\models\onnx: C:\Apps\ComfyUI_windows_portable\ComfyUI\models\tensorrt\upscaler
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[E] ModelImporter.cpp:780: Input is not a regular file: C:\Apps\ComfyUI_windows_portable\ComfyUI\models\onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
Traceback (most recent call last):
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\export_trt.py", line 29, in <module>
    export_trt()
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\export_trt.py", line 16, in export_trt
    ret = engine.build(
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\utilities.py", line 188, in build
    network = network_from_onnx_path(
  File "<string>", line 3, in network_from_onnx_path
  File "C:\Users\jjj\AppData\Local\Programs\Python\Python310\lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "C:\Users\jjj\AppData\Local\Programs\Python\Python310\lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\jjj\AppData\Local\Programs\Python\Python310\lib\site-packages\polygraphy\backend\trt\loader.py", line 247, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "C:\Users\jjj\AppData\Local\Programs\Python\Python310\lib\site-packages\polygraphy\backend\trt\util.py", line 88, in check_onnx_parser_errors
    G_LOGGER.critical(
  File "C:\Users\jjj\AppData\Local\Programs\Python\Python310\lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
```

I downloaded a couple .onnx files from here and placed them in the \models\onnx folder:
https://huggingface.co/yuvraj108c/ComfyUI-Upscaler-Onnx/tree/main

I'm assuming it should create .engine files and place it in the \models\tensorrt\upscaler folder, but it's empty. Am I missing something?

**Comment by yuvraj108c** [comment]
Hi, you need to enter the full path of the models, not the directory!
e.g
C:\Apps\ComfyUI_windows_portable\ComfyUI\models\onnx\4x_upscaler.onnx

**Comment by yuvraj108c** [comment]
Share your full logs
It seems that you haven't set the full path for the engine: : 'C:\AI_Files\ComfyUI\models\onnx\engine'

the path should end with .engine

**Comment by yuvraj108c** [comment]
ok you figured it out
