### ISSUE TITLE
node types were not found: UpscalerTensorrt

### ISSUE THREAD

**Issue by ganauou** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#7]
[ERROR] An error occurred while retrieving information for the 'UpscalerTensorrt' node.
Traceback (most recent call last):
  File "G:\AI\comfy2\ComfyUI_windows_portable\ComfyUI\server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "G:\AI\comfy2\ComfyUI_windows_portable\ComfyUI\server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\comfy2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 16, in INPUT_TYPES
    "engine": (os.listdir(ENGINE_DIR),),
               ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'G:\\AI\\comfy2\\ComfyUI_windows_portable\\ComfyUI\\models\\tensorrt\\upscaler'
![image](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/assets/6640187/98c04f79-1053-4201-b557-26ac90c8fd67)

**Comment by yuvraj108c** [comment]
Hi, you need to follow the steps in the readme, then place the tensorrt engines inside

`'G:\AI\comfy2\ComfyUI_windows_portable\ComfyUI\models\tensorrt\upscaler'
